'use strict';
let libQ;
try { libQ = require('/volumio/node_modules/kew'); } catch (e) { libQ = require('kew'); }
const ConfigStore=require('./lib/config-store'); const {execFile}=require('child_process'); const {SurfaceDial}=require('./lib/surface-dial'); const bluetooth=require('./lib/bluetooth');
module.exports=ControllerSurfaceDial;
function ControllerSurfaceDial(context){this.context=context;this.commandRouter=context.coreCommand;this.logger=context.logger;this.configManager=context.configManager;this.config=new ConfigStore();this.dial=null;this.buttonDownAt=null;this.clickTimer=null;this.pendingClicks=0;this.longPressFired=false;this.volumeTarget=null;this.volumeInitialising=false;this.pendingRotation=0;this.volumeFlushTimer=null;this.bluetoothReconnectTimer=null;this.bluetoothReconnectBusy=false;}
ControllerSurfaceDial.prototype._resolvedLifecyclePromise=function(){const defer=libQ.defer();defer.resolve();return defer.promise;};
ControllerSurfaceDial.prototype._hapticsEnabled=function(){const value=this.config.get('haptics');return typeof value==='undefined'?true:!!value;};
ControllerSurfaceDial.prototype.onVolumioStart=function(){const configFile=this.commandRouter.pluginManager.getConfigurationFile(this.context,'config.json');this.config.loadFile(configFile);return this._resolvedLifecyclePromise();};
ControllerSurfaceDial.prototype.onStart=function(){const reconnectMs=Math.max(1000,Number(this.config.get('reconnect_seconds')||5)*1000);this.volumeTarget=null;this.pendingRotation=0;this.volumeInitialising=false;this.dial=new SurfaceDial({logger:this.logger,reconnectMs,stepsPerRevolution:50,autoHaptic:this._hapticsEnabled(),onRotation:this._onRotation.bind(this),onButton:this._onButton.bind(this),onDisconnect:this._resetButtonState.bind(this)});this.dial.start();this._startBluetoothReconnectWatch(reconnectMs);this.logger.info('[Surface Dial] Plugin started: 50 detents/revolution, 2% volume per detent, haptics '+(this._hapticsEnabled()?'on':'off'));return this._resolvedLifecyclePromise();};
ControllerSurfaceDial.prototype.onStop=function(){if(this.clickTimer)clearTimeout(this.clickTimer);if(this.volumeFlushTimer)clearTimeout(this.volumeFlushTimer);if(this.bluetoothReconnectTimer)clearInterval(this.bluetoothReconnectTimer);this.clickTimer=null;this.volumeFlushTimer=null;this.bluetoothReconnectTimer=null;this.bluetoothReconnectBusy=false;this.buttonDownAt=null;this.pendingClicks=0;this.pendingRotation=0;this.volumeTarget=null;if(this.dial)this.dial.stop();this.dial=null;this.logger.info('[Surface Dial] Plugin stopped');return this._resolvedLifecyclePromise();};
ControllerSurfaceDial.prototype._startBluetoothReconnectWatch=function(reconnectMs){if(this.bluetoothReconnectTimer)clearInterval(this.bluetoothReconnectTimer);const interval=Math.max(2000,reconnectMs);this.bluetoothReconnectTimer=setInterval(()=>{if(!this.dial||this.dial.isConnected()||this.bluetoothReconnectBusy)return;const mac=this.config.get('device_mac');if(!mac)return;this.bluetoothReconnectBusy=true;bluetooth.connect(mac).then(()=>{this.logger.info('[Surface Dial] Bluetooth connection restored');}).catch(err=>{this.logger.debug('[Surface Dial] Bluetooth reconnect pending: '+(err&&err.message?err.message:err));}).then(()=>{this.bluetoothReconnectBusy=false;});},interval);};
ControllerSurfaceDial.prototype.getConfigurationFiles=function(){return ['config.json'];};
ControllerSurfaceDial.prototype.getUIConfig=function(){const defer=libQ.defer();const langCode=this.commandRouter.sharedVars.get('language_code');this.commandRouter.i18nJson(__dirname+'/i18n/strings_'+langCode+'.json',__dirname+'/i18n/strings_en.json',__dirname+'/UIConfig.json').then(uiconf=>{const values={device_mac:this.config.get('device_mac')||'',reverse_rotation:!!this.config.get('reverse_rotation'),haptics:this._hapticsEnabled(),double_press_ms:Number(this.config.get('double_press_ms')||420),long_press_ms:Number(this.config.get('long_press_ms')||700),reconnect_seconds:Number(this.config.get('reconnect_seconds')||5)};uiconf.sections.forEach(section=>section.content.forEach(item=>{if(Object.prototype.hasOwnProperty.call(values,item.id))item.value=values[item.id];if(['single_press','double_press','long_press'].includes(item.id)){const raw=this.config.get(item.id)||'none';const option=(item.options||[]).find(o=>o.value===raw);if(option)item.value=option;}}));defer.resolve(uiconf);}).fail(err=>{this.logger.error('[Surface Dial] Could not load UI configuration: '+(err&&err.message?err.message:err));defer.reject(err||new Error('Unable to load UI configuration'));});return defer.promise;};
ControllerSurfaceDial.prototype.saveSettings=function(data){const getValue=key=>{const v=data[key];return v&&typeof v==='object'&&Object.prototype.hasOwnProperty.call(v,'value')?v.value:v;};const keys=['device_mac','reverse_rotation','single_press','double_press','long_press','double_press_ms','long_press_ms','reconnect_seconds','haptics'];keys.forEach(key=>{if(typeof data[key]!=='undefined')this.config.set(key,getValue(key));});const reconnectMs=Math.max(1000,Number(this.config.get('reconnect_seconds')||5)*1000);if(this.dial){this.dial.setReconnectMs(reconnectMs);this.dial.setHaptics(this._hapticsEnabled());}this._startBluetoothReconnectWatch(reconnectMs);this.commandRouter.pushToastMessage('success','Surface Dial','Settings saved');return this._resolvedLifecyclePromise();};
ControllerSurfaceDial.prototype.scanForDial=function(){this.commandRouter.pushToastMessage('info','Surface Dial','Scanning for Surface Dial… Put the Dial into pairing mode.');return bluetooth.scanForSurfaceDial().then(devices=>{if(!devices.length){this.commandRouter.pushToastMessage('warning','Surface Dial','No Surface Dial found. Hold its pairing button and try again.');return;}const found=devices[0];this.config.set('device_mac',found.mac);this.commandRouter.pushToastMessage('success','Surface Dial','Found '+found.name+' ('+found.mac+'). Re-open settings, then press Pair.');}).catch(err=>{this.commandRouter.pushToastMessage('error','Surface Dial','Scan failed: '+err.message);throw err;});};
ControllerSurfaceDial.prototype.pairDial=function(data){const mac=(data&&data.device_mac)||this.config.get('device_mac');if(!mac){this.commandRouter.pushToastMessage('error','Surface Dial','No Bluetooth address selected. Scan first.');return this._resolvedLifecyclePromise();}this.config.set('device_mac',mac);return bluetooth.pair(mac).then(()=>{this.commandRouter.pushToastMessage('success','Surface Dial','Pairing completed. Automatic wake/reconnect is enabled.');}).catch(err=>{this.commandRouter.pushToastMessage('error','Surface Dial','Pairing failed: '+err.message);throw err;});};
ControllerSurfaceDial.prototype.forgetDial=function(data){const mac=(data&&data.device_mac)||this.config.get('device_mac');if(!mac)return this._resolvedLifecyclePromise();return bluetooth.forget(mac).then(()=>{this.config.set('device_mac','');this.commandRouter.pushToastMessage('success','Surface Dial','Surface Dial removed from Bluetooth devices.');}).catch(err=>{this.commandRouter.pushToastMessage('error','Surface Dial','Could not remove device: '+err.message);throw err;});};
ControllerSurfaceDial.prototype._onRotation=function(direction){let dir=direction;if(this.config.get('reverse_rotation'))dir*=-1;this.pendingRotation+=dir;if(this.volumeTarget!==null){this._applyPendingRotation();return;}if(this.volumeInitialising)return;this.volumeInitialising=true;this.commandRouter.volumioretrievevolume().then(volume=>{const current=Number(volume&&volume.vol);this.volumeInitialising=false;if(!Number.isFinite(current)){this.pendingRotation=0;this.logger.error('[Surface Dial] Could not read current Volumio volume');return;}this.volumeTarget=current;this._applyPendingRotation();}).fail(err=>{this.volumeInitialising=false;this.pendingRotation=0;this.logger.error('[Surface Dial] Volume adjustment failed: '+(err&&err.message?err.message:err));});};
ControllerSurfaceDial.prototype._applyPendingRotation=function(){if(this.volumeTarget===null||!this.pendingRotation)return;const delta=this.pendingRotation*2;this.pendingRotation=0;this.volumeTarget=Math.max(0,Math.min(100,this.volumeTarget+delta));if(this.volumeFlushTimer)clearTimeout(this.volumeFlushTimer);this.volumeFlushTimer=setTimeout(()=>{this.volumeFlushTimer=null;this.commandRouter.volumiosetvolume(this.volumeTarget);},12);};
ControllerSurfaceDial.prototype._resetButtonState=function(){if(this.clickTimer)clearTimeout(this.clickTimer);this.clickTimer=null;this.buttonDownAt=null;this.pendingClicks=0;this.longPressFired=false;};
ControllerSurfaceDial.prototype._onButton=function(pressed){const now=Date.now();if(pressed){if(this.buttonDownAt!==null)return;this.buttonDownAt=now;this.longPressFired=false;return;}if(this.buttonDownAt===null)return;const held=now-this.buttonDownAt;this.buttonDownAt=null;const longMs=Math.max(300,Number(this.config.get('long_press_ms')||700));if(held>=longMs){this.longPressFired=true;this.pendingClicks=0;if(this.clickTimer)clearTimeout(this.clickTimer);this.clickTimer=null;this._performAction(this.config.get('long_press')||'previous');return;}this.pendingClicks+=1;const doubleMs=Math.max(200,Number(this.config.get('double_press_ms')||420));if(this.pendingClicks>=2){if(this.clickTimer)clearTimeout(this.clickTimer);this.clickTimer=null;this.pendingClicks=0;this._performAction(this.config.get('double_press')||'next');return;}this.clickTimer=setTimeout(()=>{this.clickTimer=null;if(this.pendingClicks===1)this._performAction(this.config.get('single_press')||'toggle');this.pendingClicks=0;},doubleMs);};
ControllerSurfaceDial.prototype._performAction=function(action){switch(action){case 'toggle':this._volumioCli(['toggle']);break;case 'next':this._volumioCli(['next']);break;case 'previous':this._volumioCli(['previous']);break;case 'none':default:break;}if(this._hapticsEnabled()&&this.dial)this.dial.impact(0);};
ControllerSurfaceDial.prototype._volumioCli=function(args){execFile('/usr/local/bin/volumio',args,{timeout:5000},(err,stdout,stderr)=>{if(err)this.logger.error('[Surface Dial] Volumio command failed: '+(stderr||err.message));});};
